FROM postgres:15.3
ENV POSTGRES_DB=master_diabet
ENV POSTGRES_USER=master_diabet_user
ENV POSTGRES_PASSWORD=Y#8f!6a3
RUN mkdir /var/lib/postgresql/backup
RUN chown -R postgres /var/lib/postgresql/backup